# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout-ui-extensions"
client_id = "aa54b53ca9452ae644c0aaf2eff72c59"
application_url = "https://digit-routers-soldiers-discovered.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://digit-routers-soldiers-discovered.trycloudflare.com/auth/callback",
  "https://digit-routers-soldiers-discovered.trycloudflare.com/auth/shopify/callback",
  "https://digit-routers-soldiers-discovered.trycloudflare.com/api/auth/callback",
  "https://digit-routers-soldiers-discovered.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extensibility-hands-on-workshop.myshopify.com"
